name: CI/CD Pipeline - Prova Service

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov

      - name: Rodar testes
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: pytest

      - name: Login no DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build e Push da imagem
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/zambomprova:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/zambomprova:latest

      - name: Configurar SSH para EC2
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.KEY_TEST }}

      - name: Deploy na EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.HOST_TEST }} << EOF
          docker pull --no-cache ${{ secrets.DOCKERHUB_USERNAME }}/zambomprova:latest
          docker stop zambomprova || true
          docker rm zambomprova || true
          docker run -d -p 8081:5001 \
            -e MONGO_URI=${{ secrets.MONGO_URI }} \
            --name zambomprova \
            ${{ secrets.DOCKERHUB_USERNAME }}/zambomprova:latest
          EOF